=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/dyna-metadata/props-metadata.dtd
<!ELEMENT meta-data (table)*>
<!ATTLIST meta-data
      property-table CDATA #REQUIRED
      >

<!ELEMENT table (entity* ) >
<!ATTLIST table
      name CDATA #REQUIRED
      >

<!ELEMENT entity ((past-name*), (locator-option?), label, description, (property*)) >
<!ATTLIST entity
      type CDATA #REQUIRED
      is-abstract CDATA "false"
      extends CDATA ""
      child-locator-key CDATA ""
      locator-value CDATA ""
      is-analytic CDATA "true"
      has-attributes CDATA "false"
      >

<!ELEMENT past-name (#PCDATA)>

<!ELEMENT label (#PCDATA)>
<!ATTLIST label
      idtag CDATA "">

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
      idtag CDATA "">

<!ELEMENT property ((past-name*), label, description, type-definition, (select*)?) >
<!ATTLIST property
      key CDATA #REQUIRED
      column-name CDATA ""
      is-visible CDATA "true"
      is-mandatory CDATA "false"
	  is-cycle-control CDATA "false"
	  is-analytic CDATA "true"
      display-type CDATA ""
      >

<!ELEMENT type-definition (#PCDATA) >

<!ELEMENT select (option*)>
<!ATTLIST select
      is-bound CDATA "true"
      >

<!ELEMENT option (#PCDATA)>
<!ATTLIST option
      value CDATA #REQUIRED
      is-default CDATA "false"
      idtag CDATA "">

<!ELEMENT locator-option (#PCDATA)>
<!ATTLIST locator-option
      value CDATA #REQUIRED
      is-default CDATA "false"
      idtag CDATA "">

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/physical-metadata-samsys.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
  <table name="device">

    <entity type="SamsysMP9320ReaderDeviceNode" extends="RFDeviceNode">
      <locator-option value="Samsys MP9320 Reader DeviceNode">Samsys MP9320 Reader DeviceNode</locator-option>

      <label>Samsys MP 9320 DeviceNode Configuration</label>
      <description>Samsys MP 9320 DeviceNode Configuration</description>
      <property key="AntennaId" is-mandatory="true">
	<label>Antenna ID</label>
	<description>Antenna number</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="true">
	  <option value="1" is-default="true">1</option>
	  <option value="2">2</option>
	  <option value="3">3</option>
	  <option value="4">4</option>
	</select>
      </property>
      <property key="ReadTimeOut" is-mandatory="false">
	<label>Read Time-Out</label>
	<description>Time out value used for reading tag-ids</description>
	<type-definition>oat:TimeoutMillisSamsys</type-definition>
	<select is-bound="false">
	  <option value="2000" is-default="true">2000</option>
	</select>
      </property>
      <property key="TimeThreshold" is-mandatory="false">
	<label>Time Threshold</label>
	<description>The time threshold should exceed 100 milliseconds</description>
	<type-definition>oat:TimeThreshold</type-definition>
      </property>
      <property key="LoopThreshold" is-mandatory="false">
	<label>Loop Threshold</label>
	<description>The loop threshold should exceed -1</description>
	<type-definition>oat:LoopThreshold</type-definition>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/pml-metadata.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="PML">
  <table name="product">
    <entity type="ProductOld">
    <past-name>Product</past-name>
    <label>PML Product Properties</label>
    <description>PML Product Properties</description>
    </entity>
  </table>

  <table name="manufacturer">
    <entity type="Manufacturer">
    <label>PML Manufacturer Properties</label>
    <description>PML Manufacturer Properties</description>
    <property key="address" is-mandatory="false">
      <label>Headquarters Address</label>
          <description>Headquarters Address of the Manufacturer</description>
      <type-definition>oat:SmallString</type-definition>
    </property>
    <property key="address_line2" is-mandatory="false">
      <label>Address Line2</label>
          <description>Address Line2</description>
      <type-definition>oat:SmallString</type-definition>
    </property>
    <property key="address_line3" is-mandatory="false">
      <label>Address Line3</label>
          <description>Address Line3</description>
      <type-definition>oat:SmallString</type-definition>
    </property>

    <property key="website" is-mandatory="false">
      <label>Manufacture Website</label>
          <description>Manufacture Website</description>
      <type-definition>oat:WebSite</type-definition>
    </property>
    <property key="phone_number" is-mandatory="false">
      <label>Manufacturer Phone Number</label>
          <description>Manufacturer Phone Number</description>
      <type-definition>oat:PhoneNumber</type-definition>
    </property>
    <property key="contact_hours" is-mandatory="false">
      <label>Contact hours</label>
          <description>Contact hours</description>
      <type-definition>oat:SmallString</type-definition>
    </property>
    </entity>
  </table>

   <table name="asn">
    <entity type="Asn">
        <label>asn object</label>
        <description>extensions for the asn schema</description>
    </entity>
   </table>

   <table name="order_def">
    <entity type="Order">
        <label>Order</label>
        <description>An order properties</description>
        <property key="order_num" is-mandatory="false">
          <label>Order number</label>
          <description>Order number</description>
          <type-definition>oat:SmallString</type-definition>
        </property>
        <property key="customer_id" is-mandatory="false">
          <label>Customer Id</label>
          <description>Customer Id</description>
          <type-definition>oat:SmallString</type-definition>
        </property>
        <property key="status" is-mandatory="false">
          <label>Order status</label>
          <description>Order status</description>
          <type-definition>oat:SmallString</type-definition>
          <select is-bound="true">
            <option value="completed" is-default="true">Completed</option>
            <option value="shipped">Shipped</option>
            <option value="cancelled">Cancelled</option>
            <option value="error">Error</option>
          </select>
        </property>
    </entity>
   </table>
   <table name="order_li">
    <entity type="OrderLI">
        <label>Order LI</label>
        <description>An order line item properties</description>
        <property key="startEPC" is-mandatory="false">
          <label>Start EPC</label>
          <description>Starting EPC of ENMS order</description>
          <type-definition>oat:EPC</type-definition>
        </property>
        <property key="endEPC" is-mandatory="false">
          <label>End EPC</label>
          <description>Ending EPC of ENMS order</description>
          <type-definition>oat:EPC</type-definition>
        </property>
    </entity>
   </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/physical-metadata-tagsys.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
  <table name="device">

    <entity type="TagsysReaderL200DeviceNode" extends="RFDeviceNode">
      <locator-option value="Tagsys Reader L200 DeviceNode">Tagsys Reader L200 DeviceNode</locator-option>

      <label>Tagsys Reader L200 DeviceNode Configuration</label>
      <description>Tagsys Reader L200 DeviceNode Configuration</description>
      <property key="ReadDuration" is-mandatory="false">
	<label>Read Duration</label>
	<description>Time-out value used during read operations. </description>
	<type-definition>oat:ReadDuration</type-definition>
	<select is-bound="false">
	  <option value="-1" is-default="true">-1</option>
	</select>
      </property>
      <property key="RestoreIOPortsOnReset" is-mandatory="false">
	<label>Restore I/O ports after device reset</label>
	<description>Restore I/O ports after device reset</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="true" is-default="true">true</option>
	  <option value="false">false</option>
	</select>
      </property>
      <property key="ReadPullIntervalDivider" is-mandatory="false">
	<label>Read Pull Interval Divider</label>
	<description>This value used to calculate pull time, while waiting for new tags in continues read mode. Pause is ReadTimeDuration divided by this value</description>
	<type-definition>oat:ReadPullIntervalDivider</type-definition>
	<select is-bound="false">
	  <option value="3" is-default="true">3</option>
	</select>
      </property>
      <property key="AntennaId" is-mandatory="true">
	<label>Antenna ID</label>
	<description>Antenna number</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="true">
	  <option value="1" is-default="true">1</option>
	  <option value="2">2</option>
	  <option value="3">3</option>
	  <option value="4">4</option>
	</select>
      </property>
      <property key="TimeThreshold" is-mandatory="false">
	<label>Time Threshold</label>
	<description>The time threshold should exceed 100 milliseconds</description>
	<type-definition>oat:TimeThreshold</type-definition>
      </property>
      <property key="LoopThreshold" is-mandatory="false">
	<label>Loop Threshold</label>
	<description>The loop threshold should exceed -1</description>
	<type-definition>oat:LoopThreshold</type-definition>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/physical-metadata-checkpoint.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
	<table name="device">
        <!-- Checkpoint MPOS device node -->
		<entity type="CkpMPOSDeviceNode" extends="RFDeviceNode">
			<locator-option value="Checkpoint MPOS reader DeviceNode">Checkpoint MPOS reader DeviceNode</locator-option>
			<label>Checkpoint MPOS Antenna Configuration</label>
			<description>Checkpoint MPOS Antenna Configuration</description>
			<property key="AntennaId" is-mandatory="true">	
				<label>Antenna ID</label>
				<description>Antenna number</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
				  <option value="1" is-default="true">1</option>
				  <option value="2">2</option>
				  <option value="3">3</option>
				  <option value="4">4</option>
				</select>
			</property>
		</entity>		
	</table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/object-metadata.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="">
    <table name="object_state">
        <entity type="EPCObject" is-analytic="false">
            <label>EPC Object</label>
            <description>EPC Object</description>
        </entity>
    </table>
    <table name="process">
        <entity type="Process">
            <label>Process</label>
            <description>Process</description>
        </entity>
    </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/physical-metadata-wirama.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
	<table name="device">

		<entity type="WiramaReaderDeviceNode" extends="RFDeviceNode">
			<locator-option value="Wirama Reader DeviceNode">Wirama Reader DeviceNode</locator-option>

			<label>Wirama DeviceNode Configuration</label>
			<description>Wirama DeviceNode Configuration</description>
			<property key="AntennaId" is-mandatory="true">
				<label>Antenna ID</label>
				<description>Antenna number</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
					<option value="1" is-default="true">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
				</select>
			</property>
			<!-- <property key="PowerLevel" is-mandatory="false">
				<label>Power level</label>
				<description>RF power level for the reader (in percentage)</description>
				<type-definition>oat:Percentage</type-definition>
				<select is-bound="false">
					<option value="100" is-default="true">100%</option>
				</select>
			</property>
			<property key="WiramaInvCount" is-mandatory="false">
				<label>Inventory count</label>
				<description>Number of Inventory read count per read cycle</description>
				<type-definition>oat:WiramaInvCount</type-definition>
				<select is-bound="false">
					<option value="5" is-default="true">5</option>
				</select>
			</property>
			 <property key="WiramaRxAntenna" is-mandatory="false">
				<label>Receive antenna</label>
				<description>Receive antenna for inventory</description>
				<type-definition>oat:WiramaRxAntenna</type-definition>
				<select is-bound="true">
					<option value="1" is-default="true">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
				</select>
			</property>-->
			<property key="TimeThreshold" is-mandatory="false">
				<label>Time Threshold</label>
				<description>The time threshold should exceed 100 milliseconds</description>
				<type-definition>oat:TimeThreshold</type-definition>
			</property>
			<property key="LoopThreshold" is-mandatory="false">
				<label>Loop Threshold</label>
				<description>The loop threshold should exceed -1</description>
				<type-definition>oat:LoopThreshold</type-definition>
			</property>
		</entity>
		<entity type="WiramaReaderPoExDeviceNode" extends="RFDeviceNode">
			<locator-option value="Wirama PoEx Reader DeviceNode">Wirama PoEx Reader DeviceNode</locator-option>

			<label>Wirama PoEx DeviceNode Configuration</label>
			<description>Wirama PoEx DeviceNode Configuration</description>
			<property key="AntennaId" is-mandatory="true">
				<label>Antenna ID</label>
				<description>Antenna number</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
					<option value="1" is-default="true">1</option>
				</select>
			</property>
		</entity>
		
		<entity type="WiramaMonReaderDeviceNode" extends="RFDeviceNode">
			<locator-option value="Wirama Mon Reader DeviceNode">Wirama Monitoring Only Reader DeviceNode</locator-option>
			<label>Wirama Monitoring DeviceNode Configuration</label>
			<description>Wirama Monitoring DeviceNode Configuration</description>
			<property key="AntennaId" is-mandatory="true">
				<label>Antenna ID</label>
				<description>Antenna number</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
					<option value="1" is-default="true">1</option>
				</select>
			</property>
		</entity>
		
		<!--  Wirama reader driver for DC application -->
		<entity type="WiramaTunnelReaderDeviceNode" extends="RFDeviceNode">
			<locator-option value="Wirama Tunnel Reader DeviceNode">Wirama Tunnel Reader DeviceNode</locator-option>
			<label>Wirama Reader Antenna Configuration</label>
			<description>Wirama Reader Antenna Configuration</description>
			<property key="AntennaId" is-mandatory="true">
				<label>Antenna ID</label>
				<description>Antenna number</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
					<option value="1" is-default="true">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
				</select>
			</property>
		</entity>	
	</table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/physical-metadata-impinj_encode.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
	<table name="device">
        <!-- Impinj Encoder device node -->
		<entity type="ImpinjEncoderDeviceNode" extends="RFDeviceNode">
			<locator-option value="Impinj Encoder DeviceNode">Impinj Encoder DeviceNode</locator-option>
			<label>Impinj Encoder DeviceNode Configuration</label>
			<description>Impinj Encoder DeviceNode Configuration</description>
			<property key="AntennaId" is-mandatory="true">
				<label>Antenna ID</label>
				<description>Antenna number</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
					<option value="1" is-default="true">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
				</select>
			</property>
						
			<!--  Receive sensitivity -->
			<property key="ReceiveSensitivity" is-mandatory="false">
				<label>Encoder receive sensitivity</label>
				<description>Encoder receive sensitivity</description>
				<type-definition>oat:ReceiveSensitivity</type-definition>
				<select is-bound="false">
					<option value="1" is-default="true">1</option>
				</select>
			</property>
			
			<!-- Power Level for Write, Kill -->
			<property key="WritePowerLevel" is-mandatory="false">
				<label>Power level</label>
				<description>Power level </description>
				<type-definition>oat:ImpinjPowerLevel</type-definition>
				<select is-bound="false">
					<option value="87" is-default="true">87</option>
				</select>
			</property>
			
			<!--  Receive sensitivity for read -->
			<property key="ReadReceiveSensitivity" is-mandatory="false">
				<label>Reader receive sensitivity</label>
				<description>Reader receive sensitivity</description>
				<type-definition>oat:ReceiveSensitivity</type-definition>
				<select is-bound="false">
					<option value="1" is-default="true">1</option>
				</select>
			</property>
			
			
			<!-- Power Level for Read -->
			<property key="ReadPowerLevel" is-mandatory="false">
				<label>Read Power level</label>
				<description>Read Power level </description>
				<type-definition>oat:ImpinjPowerLevel</type-definition>
				<select is-bound="false">
					<option value="87" is-default="true">87</option>
				</select>
			</property>
			
			<!-- Power Level for Read -->
			<property key="ReadPowerLevel2" is-mandatory="false">
				<label>Non-RFID Read Power level</label>
				<description>Non-RFID Read Power level </description>
				<type-definition>oat:ImpinjPowerLevel</type-definition>
				<select is-bound="false">
					<option value="69" is-default="true">69</option>
				</select>
			</property>
			
			
			<property key="TimeThreshold" is-mandatory="false">
				<label>Time Threshold</label>
				<description>The time threshold should exceed 100 milliseconds</description>
				<type-definition>oat:TimeThreshold</type-definition>
			</property>
			<property key="LoopThreshold" is-mandatory="false">
				<label>Loop Threshold</label>
				<description>The loop threshold should exceed -1</description>
				<type-definition>oat:LoopThreshold</type-definition>
				<select is-bound="false">
					<option value="999999" is-default="true">999999</option>
				</select>
			</property>
			
				<!-- Use the antenna for read -->
			<property key="UseRead" is-mandatory="false">
				<label>Use antenna for read</label>
				<description>Use antenna for read</description>
				<type-definition>xsd:boolean</type-definition>
				<select is-bound="true">
					<option value="true" is-default="true">Yes</option>
					<option value="false">No</option>
				</select>
			</property>
			
			
				<!-- Use the antenna for Encode -->
			<property key="UseEncode" is-mandatory="false">
				<label>Use antenna for encode</label>
				<description>Use antenna for encode</description>
				<type-definition>xsd:boolean</type-definition>
				<select is-bound="true">
					<option value="true" is-default="true">Yes</option>
					<option value="false">No</option>
				</select>
			</property>
		</entity>		
	</table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/logical-metadata.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd"> 

<meta-data property-table="Logical">
  <table name="assn_handler">
    <entity type="Associations">
	<label>Associations configuration</label>
	<description>Associations configuration</description>
	<property key="name" column-name="handler_name" is-mandatory="true">
	  <label>Name</label>
          <description>The name of the Association</description>
	  <type-definition>oat:UnitName</type-definition>
	</property>
	<property key="description" column-name="description" is-mandatory="false">
	  <label>Description of the association</label>
          <description>Description of the association</description>
	  <type-definition>oat:Description</type-definition>
	</property>
	<property key="args" column-name="args" is-mandatory="false">
	  <label>Description of the association</label>
          <description>Description of the association</description>
	  <type-definition>xsd:string</type-definition>
	</property>
	<property key="type" column-name="handler_type" is-mandatory="true">
	  <label>The type of the association handler</label>
          <description>type is used to find the appropriate class to instantiate for this association handler.</description>
	  <type-definition>xsd:string</type-definition>
	  <select>
	    <option value="SimpleAssnHandler" is-default="true">SimpleAssnHandler</option>
	    <option value="CustomAssnHandler">ExceptionAssnHandler</option>
	  </select>
	</property>
    </entity>
  </table>
  <table name="assn_handler_location">
    <entity type="AssociationLocations">
	  <label>Associations Locations configuration</label>
	  <description>Associations Locations configuration</description>
    </entity>
  </table>

</meta-data>
