=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/dyna-metadata/props-metadata.dtd
<!ELEMENT meta-data (table)*>
<!ATTLIST meta-data
      property-table CDATA #REQUIRED
      >

<!ELEMENT table (entity* ) >
<!ATTLIST table
      name CDATA #REQUIRED
      >

<!ELEMENT entity ((past-name*), (locator-option?), label, description, (property*)) >
<!ATTLIST entity
      type CDATA #REQUIRED
      is-abstract CDATA "false"
      extends CDATA ""
      child-locator-key CDATA ""
      locator-value CDATA ""
      is-analytic CDATA "true"
      has-attributes CDATA "false"
      >

<!ELEMENT past-name (#PCDATA)>

<!ELEMENT label (#PCDATA)>
<!ATTLIST label
      idtag CDATA "">

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
      idtag CDATA "">

<!ELEMENT property ((past-name*), label, description, type-definition, (select*)?) >
<!ATTLIST property
      key CDATA #REQUIRED
      column-name CDATA ""
      is-visible CDATA "true"
      is-mandatory CDATA "false"
	  is-cycle-control CDATA "false"
	  is-analytic CDATA "true"
      display-type CDATA ""
      >

<!ELEMENT type-definition (#PCDATA) >

<!ELEMENT select (option*)>
<!ATTLIST select
      is-bound CDATA "true"
      >

<!ELEMENT option (#PCDATA)>
<!ATTLIST option
      value CDATA #REQUIRED
      is-default CDATA "false"
      idtag CDATA "">

<!ELEMENT locator-option (#PCDATA)>
<!ATTLIST locator-option
      value CDATA #REQUIRED
      is-default CDATA "false"
      idtag CDATA "">

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/dms-metadata-symbol.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
  <table name="dms_device">

    <entity type="SymbolScannerLS4000i" extends="BarcodeScanner">
      <locator-option value="Symbol Scanner LS4000i" is-default="true">Symbol Scanner LS4000i</locator-option>

      <label>Symbol Scanner LS4000i</label>
      <description>Symbol Scanner LS4000i Configuration </description>
      <property key="DefaultTimeOut" is-mandatory="false">
	<label>Default Time Out</label>
	<description>Default time-out value.  Integer between 1 and 60000</description>
	<type-definition>oat:ScannerTimeoutMillis</type-definition>
	<select is-bound="false">
	  <option value="2000" is-default="true">2000</option>
	</select>
      </property>
      <property key="PollInterval" is-mandatory="false">
	<label>Poll Interval</label>
	<description>Time to Sleep between two consecutive polls. Integer between 1 and 60000.</description>
	<type-definition>oat:SymbolPollInterval</type-definition>
	<select is-bound="false">
	  <option value="20" is-default="true">20</option>
	</select>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/physical-metadata-ems.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
  <table name="device">

    <entity type="EMSLRP820DeviceNode" extends="RFDeviceNode">
      <locator-option value="EMS LRP-820 DeviceNode">EMS LRP-820 DeviceNode</locator-option>

      <label>EMS LRP-820 DeviceNode Configuration</label>
      <description>EMS LRP-820 DeviceNode Configuration</description>
      <property key="ReadTimeOut" is-mandatory="false">
	<label>Read Time-Out</label>
	<description>Read command time-out value. Integer between 0 and 120000; default 2000</description>
	<type-definition>oat:ReadTimeoutMillis1</type-definition>
	<select is-bound="false">
	  <option value="2000" is-default="true">2000</option>
	</select>
      </property>
      <property key="AnticollisionIndex" is-mandatory="false">
	<label>Anticollision Index</label>
	<description>I-Code1 Anti-collision index. Anti collision index - Max no of tags:  0 maps to 1 ( disabled ), 1 maps to 2-4, 2 maps to 4-8, 3 maps to 8-16, 4 maps to 16-32 5 maps to 32-64, 6 maps to 64-128, 7 maps to > 128 </description>
	<type-definition>oat:ReaderNodeID</type-definition>
	<select is-bound="false">
	  <option value="00" is-default="true">00</option>
	</select>
      </property>
      <property key="FamilyCode" is-mandatory="false">
	<label>Family Code</label>
	<description>Code1 Family code. If this is 0 then command is broad cast to all tags in the field. If non zero then only the tags with the specified family id will respond.</description>
	<type-definition>oat:ReaderNodeID</type-definition>
	<select is-bound="false">
	  <option value="00" is-default="true">00</option>
	</select>
      </property>
      <property key="TimeThreshold" is-mandatory="false">
	<label>Time Threshold</label>
	<description>The time threshold should exceed 100 milliseconds</description>
	<type-definition>oat:TimeThreshold</type-definition>
      </property>
      <property key="LoopThreshold" is-mandatory="false">
	<label>Loop Threshold</label>
	<description>The loop threshold should exceed -1</description>
	<type-definition>oat:LoopThreshold</type-definition>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/physical-metadata-zebra.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
  <table name="device">

    <entity type="ZebraPrinterZ4MDeviceNode" extends="RFDeviceNode">
      <locator-option value="Zebra Printer Z4M DeviceNode">Zebra Printer Z4M DeviceNode</locator-option>

      <label>Zebra Printer Z4M DeviceNode Configuration</label>
      <description>Zebra Printer Z4M DeviceNode Configuration</description>
      <property key="ReadTimeOut" is-mandatory="false">
	<label>Read Time-Out</label>
	<description>Read command time-out value. Integer between 0 and 120000; default 4000</description>
	<type-definition>oat:ReadTimeoutMillis1</type-definition>
	<select is-bound="false">
	  <option value="4000" is-default="true">4000</option>
	</select>
      </property>
    </entity>

  </table>
</meta-data>
