=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/dyna-metadata/props-metadata.dtd
<!ELEMENT meta-data (table)*>
<!ATTLIST meta-data
      property-table CDATA #REQUIRED
      >

<!ELEMENT table (entity* ) >
<!ATTLIST table
      name CDATA #REQUIRED
      >

<!ELEMENT entity ((past-name*), (locator-option?), label, description, (property*)) >
<!ATTLIST entity
      type CDATA #REQUIRED
      is-abstract CDATA "false"
      extends CDATA ""
      child-locator-key CDATA ""
      locator-value CDATA ""
      is-analytic CDATA "true"
      has-attributes CDATA "false"
      >

<!ELEMENT past-name (#PCDATA)>

<!ELEMENT label (#PCDATA)>
<!ATTLIST label
      idtag CDATA "">

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
      idtag CDATA "">

<!ELEMENT property ((past-name*), label, description, type-definition, (select*)?) >
<!ATTLIST property
      key CDATA #REQUIRED
      column-name CDATA ""
      is-visible CDATA "true"
      is-mandatory CDATA "false"
	  is-cycle-control CDATA "false"
	  is-analytic CDATA "true"
      display-type CDATA ""
      >

<!ELEMENT type-definition (#PCDATA) >

<!ELEMENT select (option*)>
<!ATTLIST select
      is-bound CDATA "true"
      >

<!ELEMENT option (#PCDATA)>
<!ATTLIST option
      value CDATA #REQUIRED
      is-default CDATA "false"
      idtag CDATA "">

<!ELEMENT locator-option (#PCDATA)>
<!ATTLIST locator-option
      value CDATA #REQUIRED
      is-default CDATA "false"
      idtag CDATA "">

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/dms-metadata-mojix.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
  <table name="dms_device">
     <entity type="Mojix" extends="RTLS">
      <locator-option value="Mojix">Mojix</locator-option>
      <label>Mojix</label>
      <description>Mojix</description>
      <property key="HostName" is-mandatory="true">
        <label>Server IP address</label>
        <description>Mojix Server IP Address</description>
        <type-definition>oat:Host</type-definition>
      </property>
      <property key="CommandPort" is-mandatory="true">
        <label>Port number</label>
        <description>Mojix Server Port</description>
        <type-definition>oat:Port</type-definition>
        <select is-bound="false">
          <option value="8080" is-default="true">8080</option>
        </select>
      </property>
      <property key="DefaultTimeOut" is-mandatory="false">
		<label>Default Time-Out(ms)</label>
		<description>Default command time-out value is used unless command specific time-out value defined.</description>
		<type-definition>oat:TimeoutMillis</type-definition>
		<select is-bound="false">
		  <option value="1000" is-default="true">1000</option>
		</select>
      </property>
      <property key="UseDeviceTime" is-mandatory="false">
	    <label>Time for logging tag events</label>
	    <description>Which time to use for logging the tags, default OFS</description>
	    <type-definition>xsd:boolean</type-definition>
	    <select is-bound="true">
	      <option value="false" is-default="true">OFS</option>
	      <option value="true" >Device</option>
	    </select>
      </property>
      <property key="ReportingInterval" is-mandatory="true">
        <label>Reporting Interval (ms)</label>
        <description>Reporting Interval for location reports</description>
        <type-definition>oat:TimeThreshold</type-definition>
        <select is-bound="false">
          <option value="2000" is-default="true">2000</option>
        </select>
      </property>
      <property key="DistanceThreshold" is-mandatory="false">
        <label>Distance Threshold (ft)</label>
        <description>The time threshold should exceed 100 milliseconds</description>
        <type-definition>xsd:int</type-definition>
        <select is-bound="false">
          <option value="5" is-default="true">5</option>
        </select>
      </property>
      <property key="NotificationPort" is-mandatory="true">
        <label>Notification Port</label>
        <description>Notification port</description>
        <type-definition>oat:Port</type-definition>
        <select is-bound="false">
          <option value="8008" is-default="true">8008</option>
      </select>
      </property>
      </entity>
  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/dms-metadata-samsys.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
  <table name="dms_device">

    <entity type="SamsysMP9320Reader" extends="RFReader">
      <locator-option value="Samsys MP9320 Reader">Samsys MP9320 Reader</locator-option>

      <label>Samsys MP9320 Reader</label>
      <description>Samsys MP9320 Reader Configuration</description>
      <property key="number_of_antennas" is-mandatory="false" is-visible="false">
	<label>Maximum number of antennas</label>
	<description>Maximum number of antennas for Samsys MP9320 Reader</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="true">
	  <option value="4" is-default="true">4</option>
	</select>
      </property>
      <property key="TagType" is-mandatory="true">
	<label>Tag Type</label>
	<description>Type of tags used.</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="EPC1" is-default="true">EPC1</option>
	  <option value="IS186B">IS186B</option>
	  <option value="Philips UCODE V1.19">Philips UCODE V1.19</option>
	  <option value="EPC1G2">Gen2</option>
	  <option value="ALL">EPC1/IS186B/Gen2</option>
	</select>
      </property>
      <property key="AutoMode" is-mandatory="false">
	<label>Auto Mode</label>
	<description>True implies Continous. False implies Polled behaviour. </description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="True">Yes</option>
	  <option value="NoAction" is-default="true">No Action</option>
	</select>
      </property>
      <property key="NumberOfPassesPerRead" is-mandatory="false">
	<label>Number of passes per read</label>
	<description>The number of times to query an antenna before moving onto the next antenna</description>
	<type-definition>oat:NumberOfPassesPerReadSamsys</type-definition>
	<select is-bound="false">
	  <option value="2" is-default="true">2</option>
	</select>
      </property>
      <property key="SerialNumber" is-mandatory="false">
	<label>Serial Number</label>
	<description>Serial Number required to enable the reader to use IS186b Tags. </description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="false">
	  <option value="0" is-default="true">0</option>
	</select>
      </property>
      <property key="Session" is-mandatory="false">
	<label>Session </label>
	<description>Session </description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="false">
	  <option value="0" is-default="true">0</option>
	  <option value="1">1</option>
	  <option value="2">2</option>
	  <option value="3">3</option>
	</select>
      </property>
      
      <property key="QValue" is-mandatory="false">
	<label>Q value</label>
	<description>Q Value</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="false">
	  <option value="0">00</option>
	  <option value="1" is-default="true">01</option>
	  <option value="2">02</option>
	  <option value="3">03</option>
	  <option value="4">04</option>
	  <option value="5">05</option>
	  <option value="6">06</option>
	  <option value="7">07</option>
	  <option value="8">08</option>
	  <option value="9">09</option>
	  <option value="10">10</option>
	  <option value="11">11</option>
	  <option value="12">12</option>
	  <option value="13">13</option>
	  <option value="14">14</option>
	  <option value="15">15</option>
	</select>
      </property>
      
      <property key="SamsysARS" is-mandatory="false">
	<label>Adaptive Round Sizing </label>
	<description> Adaptive tuning of Q value </description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="True"> On </option>
	  <option is-default="true" value="False">Off</option>
	</select>
      </property>
      
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/dms-metadata-ems.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
  <table name="dms_device">

    <entity type="EMSLRP820" extends="RFReader">
      <locator-option value="EMS LRP-820">EMS LRP-820</locator-option>

      <label>EMS LRP-820</label>
      <description>EMS LRP-820 Configuration</description>
      <property key="number_of_antennas" is-mandatory="false" is-visible="false">
	<label>Maximum number of antennas</label>
	<description>Maximum number of antennas for an EMS reader</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="false">
	  <option value="1" is-default="true">1</option>
	</select>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/dms-metadata-zebra.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
  <table name="dms_device">

    <entity type="ZebraPrinterZ4M" extends="RFReader">
      <locator-option value="Zebra Printer Z4M">Zebra Printer Z4M</locator-option>

      <label>Zebra Printer Z4M</label>
      <description>Zebra Printer Z4M Configuration</description>
      <property key="number_of_antennas" is-mandatory="false" is-visible="false">
	<label>Maximum number of antennas</label>
	<description>Maximum number of antennas for a printer</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="true">
	  <option value="1" is-default="true">1</option>
	</select>
      </property>
      <property key="TagType" is-mandatory="true">
	<label>Tag Type</label>
	<description>Type of tags used.</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="Matrics 64 bit">Matrics 64 bit</option>
	  <option value="Alien Class1 64 bit" is-default="true">Alien Class1 64 bit</option>
	  <option value="I Code 1">I Code 1</option>
	  <option value="ISO 15693">ISO 15693</option>
	  <option value="Rafsec 96 bit">Rafsec 96 bit</option>
	</select>
      </property>
      <property key="LockTag" is-mandatory="false">
	<label>Lock Tag</label>
	<description>Lock tags after writing tag id </description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="true">true</option>
	  <option value="false" is-default="true">false</option>
	</select>
      </property>
      <property key="NumberOfPassesPerRead" is-mandatory="false">
	<label>Number Of Passes Per Read</label>
	<description>Number of retires for reading a tag  before throwing error.</description>
	<type-definition>oat:NumberOfPassesPerRead</type-definition>
	<select is-bound="false">
	  <option value="3" is-default="true">3</option>
	</select>
      </property>
      <property key="WriteRetryCount" is-mandatory="false">
	<label>Write Retry Count</label>
	<description>Number of retires for writing to a tag  before throwing error.</description>
	<type-definition>oat:PrinterWriteRetryCount</type-definition>
	<select is-bound="false">
	  <option value="0" is-default="true">0</option>
	</select>
      </property>
      <property key="ZPLWriteRetryCount" is-mandatory="false">
	<label>ZPL Write Retry Count</label>
	<description>Retry count for ZPL; Zebra printer takes this count and tries at device level.</description>
	<type-definition>oat:ZPLWriteRetryCount</type-definition>
	<select is-bound="false">
	  <option value="3" is-default="true">3</option>
	</select>
      </property>
      <property key="DelayBetweenReadRetries" is-mandatory="false">
	<label>Delay between Read retries</label>
	<description>Delay (in ms) between Read retries where the previous read failed</description>
	<type-definition>oat:DelayBetweenReadRetries</type-definition>
	<select is-bound="false">
	  <option value="1000" is-default="true">1000</option>
	</select>
      </property>
      <property key="DelayBetweenWriteRetries" is-mandatory="false">
	<label>Delay between Write retries</label>
	<description>Delay (in ms) between Write/Print retries where the previous write tag or print label failed</description>
	<type-definition>oat:DelayBetweenWriteRetries</type-definition>
	<select is-bound="false">
	  <option value="1000" is-default="true">1000</option>
	</select>
      </property>
      <property key="PrinterType" is-mandatory="false">
	<label>Printer Type</label>
	<description>Type Of Printer.</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="Zebra" is-default="true">Zebra</option>
	  <option value="Printronix">Printronix</option>
	</select>
      </property>
    </entity>

    <entity type="ZebraCompatibleApplicator" extends="Applicator">
      <locator-option value="Zebra Compatible Applicator">Zebra Compatible Applicator</locator-option>

      <label>Zebra Compatible Applicator</label>
      <description>Zebra Compatible Applicator Configuration </description>
      <property key="DefaultTimeOut" is-mandatory="false">
	<label>Default Time Out</label>
	<description>Default time-out value.  Integer between 1 and 60000</description>
	<type-definition>oat:TimeoutMillis1</type-definition>
	<select is-bound="false">
	  <option value="3000" is-default="true">3000</option>
	</select>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/dms-metadata-checkpoint.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
	<table name="dms_device">
		<!-- Checkpoint MPOS reader -->
		<entity type="CkpMPOS" extends="RFReader">
			<locator-option value="Checkpoint MPOS reader">Checkpoint MPOS reader</locator-option>
			<label>Checkpoint MPOS reader configuration</label>
			<description>Checkpoint MPOS reader configuration</description>
			
			<property key="number_of_antennas" is-mandatory="false"
				is-visible="false">
				<label>Maximum number of antennas</label>
				<description>Maximum number of antennas for Checkpoint MPOS reader</description>
				<type-definition>xsd:int</type-definition>
				<select is-bound="true">
					<option value="4" is-default="true">4</option>
				</select>
			</property>

			<!-- Antenna id -->
			<property key="ReaderNodeId" is-mandatory="true">
				<label>Reader Node ID </label>
				<description>Reader address. A hexadecimal number between 00 and FF.</description>
				<type-definition>oat:ReaderNodeID</type-definition>
				<select is-bound="false">
					<option value="04" is-default="true">04</option>
				</select>
			</property>
			
			<!-- Event notification port -->   
			<property key="EventPort" is-mandatory="true">
				<label>Event Port</label>
				<description>Async event notification port</description>
				<type-definition>oat:Port</type-definition>
				<select is-bound="false">
					<option value="40013" is-default="true">40013</option>
				</select>
			</property>
			
			<!-- Use the device or OFS time -->
		      <property key="UseDeviceTime" is-mandatory="false">
				<label>Event time </label>
				<description>Which time to use for logging the tags event time, default Device</description>
				<type-definition>xsd:boolean</type-definition>
				<select is-bound="true">
				  <option value="false">OFS</option>
				  <option value="true" is-default="true">Device</option>
				</select>
		     </property>
		    
		    <!-- Heartbeat interval -->   
			<property key="HeartbeatInterval" is-mandatory="true">
				<label>Heartbeat interval</label>
				<description>Heartbeat interval in seconds</description>
				<type-definition>oat:Interval</type-definition>
				<select is-bound="false">
					<option value="150" is-default="true">150</option>
				</select>
			</property>		 
		     
		</entity>
	</table>
</meta-data>

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/physical-metadata-sirit.xml
<?xml version="1.0"?>
<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
    <table name="device">
        <entity type="SiritInfinity510ReaderDeviceNode" extends="RFDeviceNode">
            <locator-option value="Sirit Infinity 510 Reader DeviceNode" is-default="true">Sirit Infinity 510 Reader DeviceNode</locator-option>
            <label>Sirit Infinity 510 Reader Device Node Configuration</label>
                <description>Sirit Infinity 510 Device Node Configuration</description>
                <property key="AntennaId" is-mandatory="true">
                    <label>Antenna ID</label>
                    <description>Antenna number</description>
                    <type-definition>xsd:int</type-definition>
                    <select is-bound="true">
                        <option value="1" is-default="true">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </property>

                <property key="TimeThreshold" is-mandatory="false">
                    <label>Time Threshold</label>
                    <description>The time threshold should exceed 100 milliseconds</description>
                    <type-definition>oat:TimeThreshold</type-definition>
                </property>

                <property key="LoopThreshold" is-mandatory="false">
                    <label>Loop Threshold</label>
                    <description>The loop threshold should exceed -1</description>
                    <type-definition>oat:LoopThreshold</type-definition>
                </property>

                <property key="TagType" is-mandatory="false">
                    <label>Tag Type</label>
                    <description>Type of Tags used</description>
                    <type-definition>oat:RegExp</type-definition>
                    <select is-bound="false">
                        <option value="0,1" is-default="true">0,1</option>
                    </select>
                </property>

                <property key="Power" is-mandatory="false">
                    <label>Power Level</label>
                    <description>Power Level Of Antenna</description>
                    <type-definition>oat:SiritPowerPercentage</type-definition>
                    <select is-bound="false">
                        <option value="0" is-default="true">0</option>
                    </select>
                </property>
                
                <property key="WritePower" is-mandatory="false">
                    <label>Power Level for write/kill</label>
                    <description>Power Level for write and kill</description>
                    <type-definition>oat:SiritPowerPercentage</type-definition>
                    <select is-bound="false">
                        <option value="0" is-default="true">0</option>
                    </select>
                </property>
        </entity>
        <entity type="SiritInfinity510NotificationReaderDeviceNode" extends="RFDeviceNode">
            <locator-option value="Sirit Infinity 510 Notification Reader DeviceNode" is-default="true">Sirit Infinity 510 Notification Reader DeviceNode</locator-option>
            <label>Sirit Infinity 510 Reader Notification Device Node Configuration</label>
                <description>Sirit Infinity 510 Notificaiotn Device Node Configuration</description>
                <property key="AntennaId" is-mandatory="true">
                    <label>Antenna ID</label>
                    <description>Antenna number</description>
                    <type-definition>xsd:int</type-definition>
                    <select is-bound="true">
                        <option value="1" is-default="true">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </property>

                <property key="TimeThreshold" is-mandatory="false">
                    <label>Time Threshold</label>
                    <description>The time threshold should exceed 100 milliseconds</description>
                    <type-definition>oat:TimeThreshold</type-definition>
                     <select is-bound="false">
	  					<option value="999999" is-default="true">999999</option>
					</select>
                </property>

                <property key="LoopThreshold" is-mandatory="false">
                    <label>Loop Threshold</label>
                    <description>The loop threshold should exceed -1</description>
                    <type-definition>oat:LoopThreshold</type-definition>
                </property>

                <property key="TagType" is-mandatory="false">
                    <label>Tag Type</label>
                    <description>Type of Tags used</description>
                    <type-definition>oat:RegExp</type-definition>
                    <select is-bound="false">
                        <option value="0,1" is-default="true">0,1</option>
                    </select>
                </property>

                <property key="Power" is-mandatory="false">
                    <label>Power Level</label>
                    <description>Power Level Of Antenna</description>
                    <type-definition>oat:Percentage1</type-definition>
                    <select is-bound="false">
                        <option value="75" is-default="true">75</option>
                    </select>
                </property>
        </entity>
    </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/src/main/resources/ofs/conf/metadata/dms-metadata-tagsys.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">

<meta-data property-table="DMS">
  <table name="dms_device">

    <entity type="TagsysReaderL200" extends="RFReader">
      <locator-option value="Tagsys Reader L200">Tagsys Reader L200</locator-option>

      <label>Tagsys Reader L200</label>
      <description>Tagsys Reader L200 Configuration</description>
      <property key="number_of_antennas" is-mandatory="false" is-visible="false">
	<label>Maximum number of antennas</label>
	<description>Maximum number of antennas for a tagsys reader</description>
	<type-definition>xsd:int</type-definition>
	<select is-bound="true">
	  <option value="4" is-default="true">4</option>
	</select>
      </property>
      <property key="ReaderNodeId" is-mandatory="false">
	<label>Reader Node Id </label>
	<description>Reader address</description>
	<type-definition>oat:ReaderNodeID</type-definition>
	<select is-bound="false">
	  <option value="01" is-default="true">01</option>
	</select>
      </property>
      <property key="PowerLevel" is-mandatory="true">
	<label>Power level</label>
	<description>RF power level for the reader (in percentage)</description>
	<type-definition>oat:Percentage</type-definition>
	<select is-bound="false">
	  <option value="30" is-default="true">30%</option>
	</select>
      </property>
      <property key="ReadDuration" is-mandatory="false">
	<label>Read Duration</label>
	<description>Time-out value used during read operations. </description>
	<type-definition>oat:ReadDuration</type-definition>
	<select is-bound="false">
	  <option value="1000" is-default="true">1000</option>
	</select>
      </property>
      <property key="Modulation" is-mandatory="false">
	<label>Modulation</label>
	<description>10% - DetectSof is disabled 100% - DetectSof is enabled</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="10%" is-default="true">DetectSof disabled</option>
	  <option value="100%">DetectSof enabled</option>
	</select>
      </property>
      <property key="DataCodding" is-mandatory="false">
	<label>Data Codding</label>
	<description>1/256 - Quiet mode is disabled 1/4 - Quiet Mode is enabled</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="1/256" is-default="true">Quiet mode disabled</option>
	  <option value="1/4">Quiet Mode enabled</option>
	</select>
      </property>
      <property key="DecoddingProcess" is-mandatory="false">
	<label>Decdding Process</label>
	<description>Mode:1 subcarrier : decoding Process #1 2 subcarriers : decoding Process #2</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="2 subcarriers" is-default="true">2 subcarriers</option>
	  <option value="1 subcarrier">1 subcarrier</option>
	</select>
      </property>
      <property key="Timeslots" is-mandatory="true">
	<label>Time slotts</label>
	<description>Defines the Number of Time Slots</description>
	<type-definition>oat:Timeslots</type-definition>
	<select is-bound="false">
	  <option value="4" is-default="true">4</option>
	</select>
      </property>
      <property key="RestoreIOPortsOnReset" is-mandatory="true">
	<label>Restore I/O ports after device reset</label>
	<description>Restore I/O ports after device reset</description>
	<type-definition>oat:SmallString</type-definition>
	<select is-bound="true">
	  <option value="true" is-default="true">true</option>
	  <option value="false">false</option>
	</select>
      </property>
      <property key="ReadPullIntervalDivider" is-mandatory="true">
	<label>Read Pull Interval Divider</label>
	<description>This value used to calculate pull time, while waiting for new tags in continues read mode. Pause is ReadTimeDuration divided by this value</description>
	<type-definition>oat:ReadPullIntervalDivider</type-definition>
	<select is-bound="false">
	  <option value="3" is-default="true">3</option>
	</select>
      </property>
    </entity>

  </table>
</meta-data>

=== narayankk/java-jenkins/configfiles/build/resources/main/ofs/conf/metadata/physical-metadata-mojix.xml
<?xml version="1.0"?>

<!DOCTYPE grammar SYSTEM "props-metadata.dtd">
<meta-data property-table="Physical">
  <table name="device">
    <entity type="RTLSDirectionalDeviceNode" extends="DeviceNode" locator-value="RTLSDirectionalDeviceNode">
      <label>Mojix</label>
      <description>Mojix</description>
      <property key="Zone" is-mandatory="true">
        <label>Mojix Zone</label>
        <description>Mojix InterrogationSpace</description>
        <type-definition>xsd:string</type-definition>
      </property>
      <property key="CoverageArea" is-mandatory="false">
        <label>Mojix zone</label>
        <description>Mojix Zone</description>
        <type-definition>xsd:string</type-definition>
      </property>
      <property key="Direction" is-mandatory="false">
         <label>Direction</label>
         <description>Direction</description>
         <type-definition>xsd:string</type-definition>
      </property>
      <property key="TimeThreshold" is-mandatory="false">
        <label>Time Threshold (ms)</label>
        <description>The time threshold should exceed 100 milliseconds</description>
        <type-definition>oat:TimeThreshold</type-definition>
        <select is-bound="false">
          <option value="2000" is-default="true">2000</option>
        </select>
      </property>
    </entity>
  </table>
</meta-data	>
